// <auto-generated />
using System;
using Glonas.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Glonas.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20220710230244_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("Glonas.Models.User", b =>
                {
                    b.Property<string>("User_id")
                        .HasColumnType("TEXT");

                    b.HasKey("User_id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Glonas.Models.UserPostStatistic", b =>
                {
                    b.Property<string>("Query_Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatePost")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("User_id")
                        .HasColumnType("TEXT");

                    b.HasKey("Query_Id");

                    b.ToTable("UserPosts");
                });

            modelBuilder.Entity("Glonas.Models.UserSignIn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateSignIn")
                        .HasColumnType("TEXT");

                    b.Property<string>("User_id")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserSignIns");
                });
#pragma warning restore 612, 618
        }
    }
}
